version: 1

project_name: stop-afk

builds:
  - id: linux
    main: ./
    goarch:
      - amd64
    goos:
      - linux
    env:
      - CGO_ENABLED=1
  - id: windows
    main: ./
    goarch:
      - amd64
    goos:
      - windows
    env:
      - CGO_ENABLED=0
checksum:
  name_template: 'checksums.txt'
archives:
    - format_overrides:
      - goos: windows
        format: zip
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
