name: Build & test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.22.0'
      - name: Install deps
        run: sudo apt install -y libasound2-dev
      - name: Build
        run: go build -v ./...